### PR TITLE
add bash completion support

### PR DESCRIPTION
**Pull request by bahamas10**
```
$ . <(./examples/conan.js completion)
$ conan 
--help      --verbose   --version   -h          -v          -x          ?           completion  crush       hear        help        see         smash 
```

needs cleanup... just wanted to commit this to get your idea on the implementation (re: ejs usage)

### CODE REVIEW

**Comment by bahamas10** [comment]
updated - removed ejs dependency

**Comment by bahamas10** [comment]
FYI this is lacking support for custom bash completion on a per-option basis

**Comment by trentm** [comment]
merged in commit b3903e127837f8a0c812eec6141747f5e9904f93

@bahamas10 I added 'complete -o default' in commit d7ca9c7448b5965463a3fb18e725ae174ca6b49b
Thoughts?

Some refactoring and docs in commit 8610afe3dfc147c9596ebd52dd1e526ab2d7c368

**Comment by trentm** [comment]
also, if it wasn't clear: this is awesome! :)

**Comment by trentm** [comment]
I'm holding off on publishing a new version until we discuss '-o default' usage at least a little bit.

**Comment by trentm** [comment]
bahamas10 is sold on "-o default". shipping this.

**Comment by bahamas10** [comment]
:+1:

**Pull request closed without merging**
